In [0]:
import numpy as np
import pandas as pd

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
import os

In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
#os.chdir('gdrive/My Drive/MIR')

In [0]:
#os.getcwd()

'/content/gdrive/My Drive/MIR'

In [0]:
#!wget http://mirg.city.ac.uk/datasets/magnatagatune/mp3.zip.001

--2019-05-24 07:14:15--  http://mirg.city.ac.uk/datasets/magnatagatune/mp3.zip.001
Resolving mirg.city.ac.uk (mirg.city.ac.uk)... 138.40.249.100
Connecting to mirg.city.ac.uk (mirg.city.ac.uk)|138.40.249.100|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1100000000 (1.0G) [application/zip]
Saving to: ‘mp3.zip.001’

mp3.zip.001         100%[===================>]   1.02G  29.4MB/s    in 39s     

2019-05-24 07:14:54 (27.1 MB/s) - ‘mp3.zip.001’ saved [1100000000/1100000000]



In [0]:
#!wget http://mirg.city.ac.uk/datasets/magnatagatune/mp3.zip.002

--2019-05-24 07:14:56--  http://mirg.city.ac.uk/datasets/magnatagatune/mp3.zip.002
Resolving mirg.city.ac.uk (mirg.city.ac.uk)... 138.40.249.100
Connecting to mirg.city.ac.uk (mirg.city.ac.uk)|138.40.249.100|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1100000000 (1.0G) [application/zip]
Saving to: ‘mp3.zip.002’

mp3.zip.002         100%[===================>]   1.02G  29.9MB/s    in 40s     

2019-05-24 07:15:36 (26.4 MB/s) - ‘mp3.zip.002’ saved [1100000000/1100000000]



In [0]:
#!wget http://mirg.city.ac.uk/datasets/magnatagatune/mp3.zip.003

--2019-05-24 07:15:38--  http://mirg.city.ac.uk/datasets/magnatagatune/mp3.zip.003
Resolving mirg.city.ac.uk (mirg.city.ac.uk)... 138.40.249.100
Connecting to mirg.city.ac.uk (mirg.city.ac.uk)|138.40.249.100|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 772769864 (737M) [application/zip]
Saving to: ‘mp3.zip.003’

mp3.zip.003         100%[===================>] 736.97M  29.4MB/s    in 28s     

2019-05-24 07:16:07 (26.0 MB/s) - ‘mp3.zip.003’ saved [772769864/772769864]



In [0]:
#os.listdir()

['file1.zip', 'file2.zip', 'file3.zip', 'magnatagatune.zip', 'magnatagatune']

In [0]:
#!#rm -r magnatagatune.zip

In [0]:
#!mv mp3.zip.001 file1.zip
#!mv mp3.zip.002 file2.zip
#!mv mp3.zip.003 file3.zip

In [0]:
#!cat file1.zip file2.zip file3.zip > magnatagatune.zip

In [0]:
#!mkdir magnatagatune

In [0]:
#os.chdir('..')

In [0]:
#!unzip magnatagatune.zip

In [0]:
##os.listdir()

In [0]:
##!mkdir magnatagatune

In [0]:
#!mv 0 magnatagatune/0
#!mv 1 magnatagatune/1
#!mv 2 magnatagatune/2
#!mv 3 magnatagatune/3
#!mv 4 magnatagatune/4
##!mv 5 magnatagatune/5
#!mv 6 magnatagatune/6
#!mv 7 magnatagatune/7
#!mv 8 magnatagatune/8
#!mv 9 magnatagatune/9
#!mv a magnatagatune/a
#!mv b magnatagatune/b
#!mv c magnatagatune/c
#!mv d magnatagatune/d
#!mv e magnatagatune/e
#!mv f magnatagatune/f

In [0]:
os.chdir('/content/gdrive/My Drive/MIR/')

In [0]:
os.listdir()
os.chdir('magnatagatune')

In [0]:
import librosa as lr
from glob import glob

In [0]:
#you need to replace 2 by your own folder which are listed in above block
audio_files = glob('2' + '/*.mp3')

In [0]:
#if len comes as 0 then don't go further there's a problem
len(audio_files)

1562

In [0]:
os.chdir('/content/gdrive/My Drive/MIR')

In [0]:
data_array = []

In [0]:
os.chdir('/content/gdrive/My Drive/MIR/magnatagatune')
for i in range (len(audio_files)):
  y, sr = lr.load(audio_files[i])
  arr = lr.feature.melspectrogram(y=y, sr=sr)
  arr = arr.reshape(1,128,1255)
  #print(arr.shape)
  data_array.append(arr)
  if i%20==0:
    print('Processed: '+str(i))

Processed: 0
Processed: 20
Processed: 40
Processed: 60
Processed: 80
Processed: 100
Processed: 120
Processed: 140
Processed: 160
Processed: 180
Processed: 200
Processed: 220
Processed: 240
Processed: 260
Processed: 280
Processed: 300
Processed: 320
Processed: 340
Processed: 360
Processed: 380
Processed: 400
Processed: 420
Processed: 440
Processed: 460
Processed: 480
Processed: 500
Processed: 520
Processed: 540
Processed: 560
Processed: 580
Processed: 600
Processed: 620
Processed: 640
Processed: 660
Processed: 680
Processed: 700
Processed: 720
Processed: 740
Processed: 760
Processed: 780
Processed: 800
Processed: 820
Processed: 840
Processed: 860
Processed: 880
Processed: 900
Processed: 920
Processed: 940
Processed: 960
Processed: 980
Processed: 1000
Processed: 1020
Processed: 1040
Processed: 1060
Processed: 1080
Processed: 1100
Processed: 1120
Processed: 1140
Processed: 1160
Processed: 1180
Processed: 1200
Processed: 1220
Processed: 1240
Processed: 1260
Processed: 1280
Processed: 1300


In [0]:
os.getcwd()

'/content/gdrive/My Drive/MIR/magnatagatune'

In [0]:
data = np.array(data_array)

In [0]:
data.shape

(1562, 1, 128, 1255)

In [0]:
os.chdir('/content/gdrive/My Drive/MIR')

In [0]:
os.listdir()

['file1.zip',
 'file2.zip',
 'file3.zip',
 'magnatagatune.zip',
 'magnatagatune',
 'MIR dataset_KRISHAN.ipynb',
 'MIR dataset_YOGESH.ipynb',
 'MIR dataset_KAUSHAL.ipynb',
 'MIR dataset_PRITAM.ipynb',
 'data0.npy',
 'data7.npy',
 'data3.npy',
 'data1.npy',
 'test.wav']

In [0]:
#replace data by data(filename) eg data0 data1 data2 dataa.....data in quotes is supposed to replaced
np.save('data2',data)

In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
import tensorflow as tf
import os
import numpy as np
import pandas as pd

In [0]:
os.listdir()

['YF.npy',
 'YE.npy',
 'YD.npy',
 'YC.npy',
 'YB.npy',
 'YA.npy',
 'Y9.npy',
 'Y8.npy',
 'Y7.npy',
 'Y6.npy',
 'Y5.npy',
 'Y4.npy',
 'Y3.npy',
 'Y2.npy',
 'Y1.npy',
 'Y0.npy']

In [0]:
os.chdir('./final_Ytrain')

In [0]:
data = np.load("Y5.npy")

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
